package Model;

import Util.Estado;

public class Transicao {

    private Estado[][] tabela_de_trasicao; // armazena a tabela de transição que define o automato do analisador
    private int numero_estados; // número de estados possíveis no automato (Linhas da tabela de transição)
    private int numero_entradas_alfabeto; // núemro de possíveis entradas (Colunas da tabela de transição)
    private int[] estados_finais; // lista com os estados finais do automato
    private String[] palavras_reservadas;// lista de palavras reservadas

    public Transicao() {
        // Assumindo que o automato não vai mudar então os valores são definidos manualmente (visto que já se sabe a estrutura da tabela)
        this.estados_finais = new int[]{1, 2, 3, 4, 5, 7, 8, 10, 11, 14, 15, 16, 17, 18, 19, 23, 24};
        this.palavras_reservadas = new String[]{"const", "var", "struct", "typedef", "procedure", "function", "return", "start", "if", "then", "else", "while",
                "scan", "print", "int", "float", "bool", "string", "true", "false", "extends"};
        this.numero_estados = 24; // Conferir estados em Util.Estado
        this.numero_entradas_alfabeto =  127; // TABELA ASCII até o 126
        this.tabela_de_trasicao = new Estado[this.numero_entradas_alfabeto][this.numero_estados];
        //Inicializa a tabela com todos os elementos setados em null
        for(int i = 0; i < this.numero_entradas_alfabeto; i++){
            for(int j = 0; j < this.numero_estados; j++){
                this.tabela_de_trasicao[i][j] = null;
            }
        }
        // Chama a função para inicializar os estados na tabela de transição com base no automato do analisador (ver arquivo .atm no dir raiz)
        this.inicializarMatriz();
    }

    private void inicializarMatriz() {
        /*  Seta os estados que envolvem transição sengindo o padrão:
                Matriz[(int)entradas][estados] = novo Estado
        */
        this.tabela_de_trasicao[(int)'a'][0] = Estado.ID;  //<Inicial> ::= a<ID>
        this.tabela_de_trasicao[(int)'a'][1] = Estado.ID;  //<ID> ::= a<ID>
        this.tabela_de_trasicao[(int)'a'][6] = Estado.comp1;  //<comp1> ::= a<comp1>
        this.tabela_de_trasicao[(int)'a'][9] = Estado.comp1;  //<comp2> ::= a<comp1>
        this.tabela_de_trasicao[(int)'a'][12] = Estado.UEV;  //<nump1> ::= a<UEV>
        this.tabela_de_trasicao[(int)'a'][13] = Estado.TMF;  //<nump2> ::= a<TMF>
        this.tabela_de_trasicao[(int)'a'][21] = Estado.cadcp1;  //<cadcp1> ::= a<cadcp1>
        this.tabela_de_trasicao[(int)'a'][22] = Estado.cadcp1;  //<cadcp2> ::= a<cadcp1>
        this.tabela_de_trasicao[(int)'b'][0] = Estado.ID;  //<Inicial> ::= b<ID>
        this.tabela_de_trasicao[(int)'b'][1] = Estado.ID;  //<ID> ::= b<ID>
        this.tabela_de_trasicao[(int)'b'][6] = Estado.comp1;  //<comp1> ::= b<comp1>
        this.tabela_de_trasicao[(int)'b'][9] = Estado.comp1;  //<comp2> ::= b<comp1>
        this.tabela_de_trasicao[(int)'b'][12] = Estado.UEV;  //<nump1> ::= b<UEV>
        this.tabela_de_trasicao[(int)'b'][13] = Estado.TMF;  //<nump2> ::= b<TMF>
        this.tabela_de_trasicao[(int)'b'][21] = Estado.cadcp1;  //<cadcp1> ::= b<cadcp1>
        this.tabela_de_trasicao[(int)'b'][22] = Estado.cadcp1;  //<cadcp2> ::= b<cadcp1>
        this.tabela_de_trasicao[(int)'c'][0] = Estado.ID;  //<Inicial> ::= c<ID>
        this.tabela_de_trasicao[(int)'c'][1] = Estado.ID;  //<ID> ::= c<ID>
        this.tabela_de_trasicao[(int)'c'][6] = Estado.comp1;  //<comp1> ::= c<comp1>
        this.tabela_de_trasicao[(int)'c'][9] = Estado.comp1;  //<comp2> ::= c<comp1>
        this.tabela_de_trasicao[(int)'c'][12] = Estado.UEV;  //<nump1> ::= c<UEV>
        this.tabela_de_trasicao[(int)'c'][13] = Estado.TMF;  //<nump2> ::= c<TMF>
        this.tabela_de_trasicao[(int)'c'][21] = Estado.cadcp1;  //<cadcp1> ::= c<cadcp1>
        this.tabela_de_trasicao[(int)'c'][22] = Estado.cadcp1;  //<cadcp2> ::= c<cadcp1>
        this.tabela_de_trasicao[(int)'d'][0] = Estado.ID;  //<Inicial> ::= d<ID>
        this.tabela_de_trasicao[(int)'d'][1] = Estado.ID;  //<ID> ::= d<ID>
        this.tabela_de_trasicao[(int)'d'][6] = Estado.comp1;  //<comp1> ::= d<comp1>
        this.tabela_de_trasicao[(int)'d'][9] = Estado.comp1;  //<comp2> ::= d<comp1>
        this.tabela_de_trasicao[(int)'d'][12] = Estado.UEV;  //<nump1> ::= d<UEV>
        this.tabela_de_trasicao[(int)'d'][13] = Estado.TMF;  //<nump2> ::= d<TMF>
        this.tabela_de_trasicao[(int)'d'][21] = Estado.cadcp1;  //<cadcp1> ::= d<cadcp1>
        this.tabela_de_trasicao[(int)'d'][22] = Estado.cadcp1;  //<cadcp2> ::= d<cadcp1>
        this.tabela_de_trasicao[(int)'e'][0] = Estado.ID;  //<Inicial> ::= e<ID>
        this.tabela_de_trasicao[(int)'e'][1] = Estado.ID;  //<ID> ::= e<ID>
        this.tabela_de_trasicao[(int)'e'][6] = Estado.comp1;  //<comp1> ::= e<comp1>
        this.tabela_de_trasicao[(int)'e'][9] = Estado.comp1;  //<comp2> ::= e<comp1>
        this.tabela_de_trasicao[(int)'e'][12] = Estado.UEV;  //<nump1> ::= e<UEV>
        this.tabela_de_trasicao[(int)'e'][13] = Estado.TMF;  //<nump2> ::= e<TMF>
        this.tabela_de_trasicao[(int)'e'][21] = Estado.cadcp1;  //<cadcp1> ::= e<cadcp1>
        this.tabela_de_trasicao[(int)'e'][22] = Estado.cadcp1;  //<cadcp2> ::= e<cadcp1>
        this.tabela_de_trasicao[(int)'f'][0] = Estado.ID;  //<Inicial> ::= f<ID>
        this.tabela_de_trasicao[(int)'f'][1] = Estado.ID;  //<ID> ::= f<ID>
        this.tabela_de_trasicao[(int)'f'][6] = Estado.comp1;  //<comp1> ::= f<comp1>
        this.tabela_de_trasicao[(int)'f'][9] = Estado.comp1;  //<comp2> ::= f<comp1>
        this.tabela_de_trasicao[(int)'f'][12] = Estado.UEV;  //<nump1> ::= f<UEV>
        this.tabela_de_trasicao[(int)'f'][13] = Estado.TMF;  //<nump2> ::= f<TMF>
        this.tabela_de_trasicao[(int)'f'][21] = Estado.cadcp1;  //<cadcp1> ::= f<cadcp1>
        this.tabela_de_trasicao[(int)'f'][22] = Estado.cadcp1;  //<cadcp2> ::= f<cadcp1>
        this.tabela_de_trasicao[(int)'g'][0] = Estado.ID;  //<Inicial> ::= g<ID>
        this.tabela_de_trasicao[(int)'g'][1] = Estado.ID;  //<ID> ::= g<ID>
        this.tabela_de_trasicao[(int)'g'][6] = Estado.comp1;  //<comp1> ::= g<comp1>
        this.tabela_de_trasicao[(int)'g'][9] = Estado.comp1;  //<comp2> ::= g<comp1>
        this.tabela_de_trasicao[(int)'g'][12] = Estado.UEV;  //<nump1> ::= g<UEV>
        this.tabela_de_trasicao[(int)'g'][13] = Estado.TMF;  //<nump2> ::= g<TMF>
        this.tabela_de_trasicao[(int)'g'][21] = Estado.cadcp1;  //<cadcp1> ::= g<cadcp1>
        this.tabela_de_trasicao[(int)'g'][22] = Estado.cadcp1;  //<cadcp2> ::= g<cadcp1>
        this.tabela_de_trasicao[(int)'h'][0] = Estado.ID;  //<Inicial> ::= h<ID>
        this.tabela_de_trasicao[(int)'h'][1] = Estado.ID;  //<ID> ::= h<ID>
        this.tabela_de_trasicao[(int)'h'][6] = Estado.comp1;  //<comp1> ::= h<comp1>
        this.tabela_de_trasicao[(int)'h'][9] = Estado.comp1;  //<comp2> ::= h<comp1>
        this.tabela_de_trasicao[(int)'h'][12] = Estado.UEV;  //<nump1> ::= h<UEV>
        this.tabela_de_trasicao[(int)'h'][13] = Estado.TMF;  //<nump2> ::= h<TMF>
        this.tabela_de_trasicao[(int)'h'][21] = Estado.cadcp1;  //<cadcp1> ::= h<cadcp1>
        this.tabela_de_trasicao[(int)'h'][22] = Estado.cadcp1;  //<cadcp2> ::= h<cadcp1>
        this.tabela_de_trasicao[(int)'i'][0] = Estado.ID;  //<Inicial> ::= i<ID>
        this.tabela_de_trasicao[(int)'i'][1] = Estado.ID;  //<ID> ::= i<ID>
        this.tabela_de_trasicao[(int)'i'][6] = Estado.comp1;  //<comp1> ::= i<comp1>
        this.tabela_de_trasicao[(int)'i'][9] = Estado.comp1;  //<comp2> ::= i<comp1>
        this.tabela_de_trasicao[(int)'i'][12] = Estado.UEV;  //<nump1> ::= i<UEV>
        this.tabela_de_trasicao[(int)'i'][13] = Estado.TMF;  //<nump2> ::= i<TMF>
        this.tabela_de_trasicao[(int)'i'][21] = Estado.cadcp1;  //<cadcp1> ::= i<cadcp1>
        this.tabela_de_trasicao[(int)'i'][22] = Estado.cadcp1;  //<cadcp2> ::= i<cadcp1>
        this.tabela_de_trasicao[(int)'j'][0] = Estado.ID;  //<Inicial> ::= j<ID>
        this.tabela_de_trasicao[(int)'j'][1] = Estado.ID;  //<ID> ::= j<ID>
        this.tabela_de_trasicao[(int)'j'][6] = Estado.comp1;  //<comp1> ::= j<comp1>
        this.tabela_de_trasicao[(int)'j'][9] = Estado.comp1;  //<comp2> ::= j<comp1>
        this.tabela_de_trasicao[(int)'j'][12] = Estado.UEV;  //<nump1> ::= j<UEV>
        this.tabela_de_trasicao[(int)'j'][13] = Estado.TMF;  //<nump2> ::= j<TMF>
        this.tabela_de_trasicao[(int)'j'][21] = Estado.cadcp1;  //<cadcp1> ::= j<cadcp1>
        this.tabela_de_trasicao[(int)'j'][22] = Estado.cadcp1;  //<cadcp2> ::= j<cadcp1>
        this.tabela_de_trasicao[(int)'k'][0] = Estado.ID;  //<Inicial> ::= k<ID>
        this.tabela_de_trasicao[(int)'k'][1] = Estado.ID;  //<ID> ::= k<ID>
        this.tabela_de_trasicao[(int)'k'][6] = Estado.comp1;  //<comp1> ::= k<comp1>
        this.tabela_de_trasicao[(int)'k'][9] = Estado.comp1;  //<comp2> ::= k<comp1>
        this.tabela_de_trasicao[(int)'k'][12] = Estado.UEV;  //<nump1> ::= k<UEV>
        this.tabela_de_trasicao[(int)'k'][13] = Estado.TMF;  //<nump2> ::= k<TMF>
        this.tabela_de_trasicao[(int)'k'][21] = Estado.cadcp1;  //<cadcp1> ::= k<cadcp1>
        this.tabela_de_trasicao[(int)'k'][22] = Estado.cadcp1;  //<cadcp2> ::= k<cadcp1>
        this.tabela_de_trasicao[(int)'l'][0] = Estado.ID;  //<Inicial> ::= l<ID>
        this.tabela_de_trasicao[(int)'l'][1] = Estado.ID;  //<ID> ::= l<ID>
        this.tabela_de_trasicao[(int)'l'][6] = Estado.comp1;  //<comp1> ::= l<comp1>
        this.tabela_de_trasicao[(int)'l'][9] = Estado.comp1;  //<comp2> ::= l<comp1>
        this.tabela_de_trasicao[(int)'l'][12] = Estado.UEV;  //<nump1> ::= l<UEV>
        this.tabela_de_trasicao[(int)'l'][13] = Estado.TMF;  //<nump2> ::= l<TMF>
        this.tabela_de_trasicao[(int)'l'][21] = Estado.cadcp1;  //<cadcp1> ::= l<cadcp1>
        this.tabela_de_trasicao[(int)'l'][22] = Estado.cadcp1;  //<cadcp2> ::= l<cadcp1>
        this.tabela_de_trasicao[(int)'m'][0] = Estado.ID;  //<Inicial> ::= m<ID>
        this.tabela_de_trasicao[(int)'m'][1] = Estado.ID;  //<ID> ::= m<ID>
        this.tabela_de_trasicao[(int)'m'][6] = Estado.comp1;  //<comp1> ::= m<comp1>
        this.tabela_de_trasicao[(int)'m'][9] = Estado.comp1;  //<comp2> ::= m<comp1>
        this.tabela_de_trasicao[(int)'m'][12] = Estado.UEV;  //<nump1> ::= m<UEV>
        this.tabela_de_trasicao[(int)'m'][13] = Estado.TMF;  //<nump2> ::= m<TMF>
        this.tabela_de_trasicao[(int)'m'][21] = Estado.cadcp1;  //<cadcp1> ::= m<cadcp1>
        this.tabela_de_trasicao[(int)'m'][22] = Estado.cadcp1;  //<cadcp2> ::= m<cadcp1>
        this.tabela_de_trasicao[(int)'n'][0] = Estado.ID;  //<Inicial> ::= n<ID>
        this.tabela_de_trasicao[(int)'n'][1] = Estado.ID;  //<ID> ::= n<ID>
        this.tabela_de_trasicao[(int)'n'][6] = Estado.comp1;  //<comp1> ::= n<comp1>
        this.tabela_de_trasicao[(int)'n'][9] = Estado.comp1;  //<comp2> ::= n<comp1>
        this.tabela_de_trasicao[(int)'n'][12] = Estado.UEV;  //<nump1> ::= n<UEV>
        this.tabela_de_trasicao[(int)'n'][13] = Estado.TMF;  //<nump2> ::= n<TMF>
        this.tabela_de_trasicao[(int)'n'][21] = Estado.cadcp1;  //<cadcp1> ::= n<cadcp1>
        this.tabela_de_trasicao[(int)'n'][22] = Estado.cadcp1;  //<cadcp2> ::= n<cadcp1>
        this.tabela_de_trasicao[(int)'o'][0] = Estado.ID;  //<Inicial> ::= o<ID>
        this.tabela_de_trasicao[(int)'o'][1] = Estado.ID;  //<ID> ::= o<ID>
        this.tabela_de_trasicao[(int)'o'][6] = Estado.comp1;  //<comp1> ::= o<comp1>
        this.tabela_de_trasicao[(int)'o'][9] = Estado.comp1;  //<comp2> ::= o<comp1>
        this.tabela_de_trasicao[(int)'o'][12] = Estado.UEV;  //<nump1> ::= o<UEV>
        this.tabela_de_trasicao[(int)'o'][13] = Estado.TMF;  //<nump2> ::= o<TMF>
        this.tabela_de_trasicao[(int)'o'][21] = Estado.cadcp1;  //<cadcp1> ::= o<cadcp1>
        this.tabela_de_trasicao[(int)'o'][22] = Estado.cadcp1;  //<cadcp2> ::= o<cadcp1>
        this.tabela_de_trasicao[(int)'p'][0] = Estado.ID;  //<Inicial> ::= p<ID>
        this.tabela_de_trasicao[(int)'p'][1] = Estado.ID;  //<ID> ::= p<ID>
        this.tabela_de_trasicao[(int)'p'][6] = Estado.comp1;  //<comp1> ::= p<comp1>
        this.tabela_de_trasicao[(int)'p'][9] = Estado.comp1;  //<comp2> ::= p<comp1>
        this.tabela_de_trasicao[(int)'p'][12] = Estado.UEV;  //<nump1> ::= p<UEV>
        this.tabela_de_trasicao[(int)'p'][13] = Estado.TMF;  //<nump2> ::= p<TMF>
        this.tabela_de_trasicao[(int)'p'][21] = Estado.cadcp1;  //<cadcp1> ::= p<cadcp1>
        this.tabela_de_trasicao[(int)'p'][22] = Estado.cadcp1;  //<cadcp2> ::= p<cadcp1>
        this.tabela_de_trasicao[(int)'q'][0] = Estado.ID;  //<Inicial> ::= q<ID>
        this.tabela_de_trasicao[(int)'q'][1] = Estado.ID;  //<ID> ::= q<ID>
        this.tabela_de_trasicao[(int)'q'][6] = Estado.comp1;  //<comp1> ::= q<comp1>
        this.tabela_de_trasicao[(int)'q'][9] = Estado.comp1;  //<comp2> ::= q<comp1>
        this.tabela_de_trasicao[(int)'q'][12] = Estado.UEV;  //<nump1> ::= q<UEV>
        this.tabela_de_trasicao[(int)'q'][13] = Estado.TMF;  //<nump2> ::= q<TMF>
        this.tabela_de_trasicao[(int)'q'][21] = Estado.cadcp1;  //<cadcp1> ::= q<cadcp1>
        this.tabela_de_trasicao[(int)'q'][22] = Estado.cadcp1;  //<cadcp2> ::= q<cadcp1>
        this.tabela_de_trasicao[(int)'r'][0] = Estado.ID;  //<Inicial> ::= r<ID>
        this.tabela_de_trasicao[(int)'r'][1] = Estado.ID;  //<ID> ::= r<ID>
        this.tabela_de_trasicao[(int)'r'][6] = Estado.comp1;  //<comp1> ::= r<comp1>
        this.tabela_de_trasicao[(int)'r'][9] = Estado.comp1;  //<comp2> ::= r<comp1>
        this.tabela_de_trasicao[(int)'r'][12] = Estado.UEV;  //<nump1> ::= r<UEV>
        this.tabela_de_trasicao[(int)'r'][13] = Estado.TMF;  //<nump2> ::= r<TMF>
        this.tabela_de_trasicao[(int)'r'][21] = Estado.cadcp1;  //<cadcp1> ::= r<cadcp1>
        this.tabela_de_trasicao[(int)'r'][22] = Estado.cadcp1;  //<cadcp2> ::= r<cadcp1>
        this.tabela_de_trasicao[(int)'s'][0] = Estado.ID;  //<Inicial> ::= s<ID>
        this.tabela_de_trasicao[(int)'s'][1] = Estado.ID;  //<ID> ::= s<ID>
        this.tabela_de_trasicao[(int)'s'][6] = Estado.comp1;  //<comp1> ::= s<comp1>
        this.tabela_de_trasicao[(int)'s'][9] = Estado.comp1;  //<comp2> ::= s<comp1>
        this.tabela_de_trasicao[(int)'s'][12] = Estado.UEV;  //<nump1> ::= s<UEV>
        this.tabela_de_trasicao[(int)'s'][13] = Estado.TMF;  //<nump2> ::= s<TMF>
        this.tabela_de_trasicao[(int)'s'][21] = Estado.cadcp1;  //<cadcp1> ::= s<cadcp1>
        this.tabela_de_trasicao[(int)'s'][22] = Estado.cadcp1;  //<cadcp2> ::= s<cadcp1>
        this.tabela_de_trasicao[(int)'t'][0] = Estado.ID;  //<Inicial> ::= t<ID>
        this.tabela_de_trasicao[(int)'t'][1] = Estado.ID;  //<ID> ::= t<ID>
        this.tabela_de_trasicao[(int)'t'][6] = Estado.comp1;  //<comp1> ::= t<comp1>
        this.tabela_de_trasicao[(int)'t'][9] = Estado.comp1;  //<comp2> ::= t<comp1>
        this.tabela_de_trasicao[(int)'t'][12] = Estado.UEV;  //<nump1> ::= t<UEV>
        this.tabela_de_trasicao[(int)'t'][13] = Estado.TMF;  //<nump2> ::= t<TMF>
        this.tabela_de_trasicao[(int)'t'][21] = Estado.cadcp1;  //<cadcp1> ::= t<cadcp1>
        this.tabela_de_trasicao[(int)'t'][22] = Estado.cadcp1;  //<cadcp2> ::= t<cadcp1>
        this.tabela_de_trasicao[(int)'u'][0] = Estado.ID;  //<Inicial> ::= u<ID>
        this.tabela_de_trasicao[(int)'u'][1] = Estado.ID;  //<ID> ::= u<ID>
        this.tabela_de_trasicao[(int)'u'][6] = Estado.comp1;  //<comp1> ::= u<comp1>
        this.tabela_de_trasicao[(int)'u'][9] = Estado.comp1;  //<comp2> ::= u<comp1>
        this.tabela_de_trasicao[(int)'u'][12] = Estado.UEV;  //<nump1> ::= u<UEV>
        this.tabela_de_trasicao[(int)'u'][13] = Estado.TMF;  //<nump2> ::= u<TMF>
        this.tabela_de_trasicao[(int)'u'][21] = Estado.cadcp1;  //<cadcp1> ::= u<cadcp1>
        this.tabela_de_trasicao[(int)'u'][22] = Estado.cadcp1;  //<cadcp2> ::= u<cadcp1>
        this.tabela_de_trasicao[(int)'v'][0] = Estado.ID;  //<Inicial> ::= v<ID>
        this.tabela_de_trasicao[(int)'v'][1] = Estado.ID;  //<ID> ::= v<ID>
        this.tabela_de_trasicao[(int)'v'][6] = Estado.comp1;  //<comp1> ::= v<comp1>
        this.tabela_de_trasicao[(int)'v'][9] = Estado.comp1;  //<comp2> ::= v<comp1>
        this.tabela_de_trasicao[(int)'v'][12] = Estado.UEV;  //<nump1> ::= v<UEV>
        this.tabela_de_trasicao[(int)'v'][13] = Estado.TMF;  //<nump2> ::= v<TMF>
        this.tabela_de_trasicao[(int)'v'][21] = Estado.cadcp1;  //<cadcp1> ::= v<cadcp1>
        this.tabela_de_trasicao[(int)'v'][22] = Estado.cadcp1;  //<cadcp2> ::= v<cadcp1>
        this.tabela_de_trasicao[(int)'w'][0] = Estado.ID;  //<Inicial> ::= w<ID>
        this.tabela_de_trasicao[(int)'w'][1] = Estado.ID;  //<ID> ::= w<ID>
        this.tabela_de_trasicao[(int)'w'][6] = Estado.comp1;  //<comp1> ::= w<comp1>
        this.tabela_de_trasicao[(int)'w'][9] = Estado.comp1;  //<comp2> ::= w<comp1>
        this.tabela_de_trasicao[(int)'w'][12] = Estado.UEV;  //<nump1> ::= w<UEV>
        this.tabela_de_trasicao[(int)'w'][13] = Estado.TMF;  //<nump2> ::= w<TMF>
        this.tabela_de_trasicao[(int)'w'][21] = Estado.cadcp1;  //<cadcp1> ::= w<cadcp1>
        this.tabela_de_trasicao[(int)'w'][22] = Estado.cadcp1;  //<cadcp2> ::= w<cadcp1>
        this.tabela_de_trasicao[(int)'x'][0] = Estado.ID;  //<Inicial> ::= x<ID>
        this.tabela_de_trasicao[(int)'x'][1] = Estado.ID;  //<ID> ::= x<ID>
        this.tabela_de_trasicao[(int)'x'][6] = Estado.comp1;  //<comp1> ::= x<comp1>
        this.tabela_de_trasicao[(int)'x'][9] = Estado.comp1;  //<comp2> ::= x<comp1>
        this.tabela_de_trasicao[(int)'x'][12] = Estado.UEV;  //<nump1> ::= x<UEV>
        this.tabela_de_trasicao[(int)'x'][13] = Estado.TMF;  //<nump2> ::= x<TMF>
        this.tabela_de_trasicao[(int)'x'][21] = Estado.cadcp1;  //<cadcp1> ::= x<cadcp1>
        this.tabela_de_trasicao[(int)'x'][22] = Estado.cadcp1;  //<cadcp2> ::= x<cadcp1>
        this.tabela_de_trasicao[(int)'y'][0] = Estado.ID;  //<Inicial> ::= y<ID>
        this.tabela_de_trasicao[(int)'y'][1] = Estado.ID;  //<ID> ::= y<ID>
        this.tabela_de_trasicao[(int)'y'][6] = Estado.comp1;  //<comp1> ::= y<comp1>
        this.tabela_de_trasicao[(int)'y'][9] = Estado.comp1;  //<comp2> ::= y<comp1>
        this.tabela_de_trasicao[(int)'y'][12] = Estado.UEV;  //<nump1> ::= y<UEV>
        this.tabela_de_trasicao[(int)'y'][13] = Estado.TMF;  //<nump2> ::= y<TMF>
        this.tabela_de_trasicao[(int)'y'][21] = Estado.cadcp1;  //<cadcp1> ::= y<cadcp1>
        this.tabela_de_trasicao[(int)'y'][22] = Estado.cadcp1;  //<cadcp2> ::= y<cadcp1>
        this.tabela_de_trasicao[(int)'z'][0] = Estado.ID;  //<Inicial> ::= z<ID>
        this.tabela_de_trasicao[(int)'z'][1] = Estado.ID;  //<ID> ::= z<ID>
        this.tabela_de_trasicao[(int)'z'][6] = Estado.comp1;  //<comp1> ::= z<comp1>
        this.tabela_de_trasicao[(int)'z'][9] = Estado.comp1;  //<comp2> ::= z<comp1>
        this.tabela_de_trasicao[(int)'z'][12] = Estado.UEV;  //<nump1> ::= z<UEV>
        this.tabela_de_trasicao[(int)'z'][13] = Estado.TMF;  //<nump2> ::= z<TMF>
        this.tabela_de_trasicao[(int)'z'][21] = Estado.cadcp1;  //<cadcp1> ::= z<cadcp1>
        this.tabela_de_trasicao[(int)'z'][22] = Estado.cadcp1;  //<cadcp2> ::= z<cadcp1>
        this.tabela_de_trasicao[(int)'A'][0] = Estado.ID;  //<Inicial> ::= A<ID>
        this.tabela_de_trasicao[(int)'A'][1] = Estado.ID;  //<ID> ::= A<ID>
        this.tabela_de_trasicao[(int)'A'][6] = Estado.comp1;  //<comp1> ::= A<comp1>
        this.tabela_de_trasicao[(int)'A'][9] = Estado.comp1;  //<comp2> ::= A<comp1>
        this.tabela_de_trasicao[(int)'A'][12] = Estado.UEV;  //<nump1> ::= A<UEV>
        this.tabela_de_trasicao[(int)'A'][13] = Estado.TMF;  //<nump2> ::= A<TMF>
        this.tabela_de_trasicao[(int)'A'][21] = Estado.cadcp1;  //<cadcp1> ::= A<cadcp1>
        this.tabela_de_trasicao[(int)'A'][22] = Estado.cadcp1;  //<cadcp2> ::= A<cadcp1>
        this.tabela_de_trasicao[(int)'B'][0] = Estado.ID;  //<Inicial> ::= B<ID>
        this.tabela_de_trasicao[(int)'B'][1] = Estado.ID;  //<ID> ::= B<ID>
        this.tabela_de_trasicao[(int)'B'][6] = Estado.comp1;  //<comp1> ::= B<comp1>
        this.tabela_de_trasicao[(int)'B'][9] = Estado.comp1;  //<comp2> ::= B<comp1>
        this.tabela_de_trasicao[(int)'B'][12] = Estado.UEV;  //<nump1> ::= B<UEV>
        this.tabela_de_trasicao[(int)'B'][13] = Estado.TMF;  //<nump2> ::= B<TMF>
        this.tabela_de_trasicao[(int)'B'][21] = Estado.cadcp1;  //<cadcp1> ::= B<cadcp1>
        this.tabela_de_trasicao[(int)'B'][22] = Estado.cadcp1;  //<cadcp2> ::= B<cadcp1>
        this.tabela_de_trasicao[(int)'C'][0] = Estado.ID;  //<Inicial> ::= C<ID>
        this.tabela_de_trasicao[(int)'C'][1] = Estado.ID;  //<ID> ::= C<ID>
        this.tabela_de_trasicao[(int)'C'][6] = Estado.comp1;  //<comp1> ::= C<comp1>
        this.tabela_de_trasicao[(int)'C'][9] = Estado.comp1;  //<comp2> ::= C<comp1>
        this.tabela_de_trasicao[(int)'C'][12] = Estado.UEV;  //<nump1> ::= C<UEV>
        this.tabela_de_trasicao[(int)'C'][13] = Estado.TMF;  //<nump2> ::= C<TMF>
        this.tabela_de_trasicao[(int)'C'][21] = Estado.cadcp1;  //<cadcp1> ::= C<cadcp1>
        this.tabela_de_trasicao[(int)'C'][22] = Estado.cadcp1;  //<cadcp2> ::= C<cadcp1>
        this.tabela_de_trasicao[(int)'D'][0] = Estado.ID;  //<Inicial> ::= D<ID>
        this.tabela_de_trasicao[(int)'D'][1] = Estado.ID;  //<ID> ::= D<ID>
        this.tabela_de_trasicao[(int)'D'][6] = Estado.comp1;  //<comp1> ::= D<comp1>
        this.tabela_de_trasicao[(int)'D'][9] = Estado.comp1;  //<comp2> ::= D<comp1>
        this.tabela_de_trasicao[(int)'D'][12] = Estado.UEV;  //<nump1> ::= D<UEV>
        this.tabela_de_trasicao[(int)'D'][13] = Estado.TMF;  //<nump2> ::= D<TMF>
        this.tabela_de_trasicao[(int)'D'][21] = Estado.cadcp1;  //<cadcp1> ::= D<cadcp1>
        this.tabela_de_trasicao[(int)'D'][22] = Estado.cadcp1;  //<cadcp2> ::= D<cadcp1>
        this.tabela_de_trasicao[(int)'E'][0] = Estado.ID;  //<Inicial> ::= E<ID>
        this.tabela_de_trasicao[(int)'E'][1] = Estado.ID;  //<ID> ::= E<ID>
        this.tabela_de_trasicao[(int)'E'][6] = Estado.comp1;  //<comp1> ::= E<comp1>
        this.tabela_de_trasicao[(int)'E'][9] = Estado.comp1;  //<comp2> ::= E<comp1>
        this.tabela_de_trasicao[(int)'E'][12] = Estado.UEV;  //<nump1> ::= E<UEV>
        this.tabela_de_trasicao[(int)'E'][13] = Estado.TMF;  //<nump2> ::= E<TMF>
        this.tabela_de_trasicao[(int)'E'][21] = Estado.cadcp1;  //<cadcp1> ::= E<cadcp1>
        this.tabela_de_trasicao[(int)'E'][22] = Estado.cadcp1;  //<cadcp2> ::= E<cadcp1>
        this.tabela_de_trasicao[(int)'F'][0] = Estado.ID;  //<Inicial> ::= F<ID>
        this.tabela_de_trasicao[(int)'F'][1] = Estado.ID;  //<ID> ::= F<ID>
        this.tabela_de_trasicao[(int)'F'][6] = Estado.comp1;  //<comp1> ::= F<comp1>
        this.tabela_de_trasicao[(int)'F'][9] = Estado.comp1;  //<comp2> ::= F<comp1>
        this.tabela_de_trasicao[(int)'F'][12] = Estado.UEV;  //<nump1> ::= F<UEV>
        this.tabela_de_trasicao[(int)'F'][13] = Estado.TMF;  //<nump2> ::= F<TMF>
        this.tabela_de_trasicao[(int)'F'][21] = Estado.cadcp1;  //<cadcp1> ::= F<cadcp1>
        this.tabela_de_trasicao[(int)'F'][22] = Estado.cadcp1;  //<cadcp2> ::= F<cadcp1>
        this.tabela_de_trasicao[(int)'G'][0] = Estado.ID;  //<Inicial> ::= G<ID>
        this.tabela_de_trasicao[(int)'G'][1] = Estado.ID;  //<ID> ::= G<ID>
        this.tabela_de_trasicao[(int)'G'][6] = Estado.comp1;  //<comp1> ::= G<comp1>
        this.tabela_de_trasicao[(int)'G'][9] = Estado.comp1;  //<comp2> ::= G<comp1>
        this.tabela_de_trasicao[(int)'G'][12] = Estado.UEV;  //<nump1> ::= G<UEV>
        this.tabela_de_trasicao[(int)'G'][13] = Estado.TMF;  //<nump2> ::= G<TMF>
        this.tabela_de_trasicao[(int)'G'][21] = Estado.cadcp1;  //<cadcp1> ::= G<cadcp1>
        this.tabela_de_trasicao[(int)'G'][22] = Estado.cadcp1;  //<cadcp2> ::= G<cadcp1>
        this.tabela_de_trasicao[(int)'H'][0] = Estado.ID;  //<Inicial> ::= H<ID>
        this.tabela_de_trasicao[(int)'H'][1] = Estado.ID;  //<ID> ::= H<ID>
        this.tabela_de_trasicao[(int)'H'][6] = Estado.comp1;  //<comp1> ::= H<comp1>
        this.tabela_de_trasicao[(int)'H'][9] = Estado.comp1;  //<comp2> ::= H<comp1>
        this.tabela_de_trasicao[(int)'H'][12] = Estado.UEV;  //<nump1> ::= H<UEV>
        this.tabela_de_trasicao[(int)'H'][13] = Estado.TMF;  //<nump2> ::= H<TMF>
        this.tabela_de_trasicao[(int)'H'][21] = Estado.cadcp1;  //<cadcp1> ::= H<cadcp1>
        this.tabela_de_trasicao[(int)'H'][22] = Estado.cadcp1;  //<cadcp2> ::= H<cadcp1>
        this.tabela_de_trasicao[(int)'I'][0] = Estado.ID;  //<Inicial> ::= I<ID>
        this.tabela_de_trasicao[(int)'I'][1] = Estado.ID;  //<ID> ::= I<ID>
        this.tabela_de_trasicao[(int)'I'][6] = Estado.comp1;  //<comp1> ::= I<comp1>
        this.tabela_de_trasicao[(int)'I'][9] = Estado.comp1;  //<comp2> ::= I<comp1>
        this.tabela_de_trasicao[(int)'I'][12] = Estado.UEV;  //<nump1> ::= I<UEV>
        this.tabela_de_trasicao[(int)'I'][13] = Estado.TMF;  //<nump2> ::= I<TMF>
        this.tabela_de_trasicao[(int)'I'][21] = Estado.cadcp1;  //<cadcp1> ::= I<cadcp1>
        this.tabela_de_trasicao[(int)'I'][22] = Estado.cadcp1;  //<cadcp2> ::= I<cadcp1>
        this.tabela_de_trasicao[(int)'J'][0] = Estado.ID;  //<Inicial> ::= J<ID>
        this.tabela_de_trasicao[(int)'J'][1] = Estado.ID;  //<ID> ::= J<ID>
        this.tabela_de_trasicao[(int)'J'][6] = Estado.comp1;  //<comp1> ::= J<comp1>
        this.tabela_de_trasicao[(int)'J'][9] = Estado.comp1;  //<comp2> ::= J<comp1>
        this.tabela_de_trasicao[(int)'J'][12] = Estado.UEV;  //<nump1> ::= J<UEV>
        this.tabela_de_trasicao[(int)'J'][13] = Estado.TMF;  //<nump2> ::= J<TMF>
        this.tabela_de_trasicao[(int)'J'][21] = Estado.cadcp1;  //<cadcp1> ::= J<cadcp1>
        this.tabela_de_trasicao[(int)'J'][22] = Estado.cadcp1;  //<cadcp2> ::= J<cadcp1>
        this.tabela_de_trasicao[(int)'K'][0] = Estado.ID;  //<Inicial> ::= K<ID>
        this.tabela_de_trasicao[(int)'K'][1] = Estado.ID;  //<ID> ::= K<ID>
        this.tabela_de_trasicao[(int)'K'][6] = Estado.comp1;  //<comp1> ::= K<comp1>
        this.tabela_de_trasicao[(int)'K'][9] = Estado.comp1;  //<comp2> ::= K<comp1>
        this.tabela_de_trasicao[(int)'K'][12] = Estado.UEV;  //<nump1> ::= K<UEV>
        this.tabela_de_trasicao[(int)'K'][13] = Estado.TMF;  //<nump2> ::= K<TMF>
        this.tabela_de_trasicao[(int)'K'][21] = Estado.cadcp1;  //<cadcp1> ::= K<cadcp1>
        this.tabela_de_trasicao[(int)'K'][22] = Estado.cadcp1;  //<cadcp2> ::= K<cadcp1>
        this.tabela_de_trasicao[(int)'L'][0] = Estado.ID;  //<Inicial> ::= L<ID>
        this.tabela_de_trasicao[(int)'L'][1] = Estado.ID;  //<ID> ::= L<ID>
        this.tabela_de_trasicao[(int)'L'][6] = Estado.comp1;  //<comp1> ::= L<comp1>
        this.tabela_de_trasicao[(int)'L'][9] = Estado.comp1;  //<comp2> ::= L<comp1>
        this.tabela_de_trasicao[(int)'L'][12] = Estado.UEV;  //<nump1> ::= L<UEV>
        this.tabela_de_trasicao[(int)'L'][13] = Estado.TMF;  //<nump2> ::= L<TMF>
        this.tabela_de_trasicao[(int)'L'][21] = Estado.cadcp1;  //<cadcp1> ::= L<cadcp1>
        this.tabela_de_trasicao[(int)'L'][22] = Estado.cadcp1;  //<cadcp2> ::= L<cadcp1>
        this.tabela_de_trasicao[(int)'M'][0] = Estado.ID;  //<Inicial> ::= M<ID>
        this.tabela_de_trasicao[(int)'M'][1] = Estado.ID;  //<ID> ::= M<ID>
        this.tabela_de_trasicao[(int)'M'][6] = Estado.comp1;  //<comp1> ::= M<comp1>
        this.tabela_de_trasicao[(int)'M'][9] = Estado.comp1;  //<comp2> ::= M<comp1>
        this.tabela_de_trasicao[(int)'M'][12] = Estado.UEV;  //<nump1> ::= M<UEV>
        this.tabela_de_trasicao[(int)'M'][13] = Estado.TMF;  //<nump2> ::= M<TMF>
        this.tabela_de_trasicao[(int)'M'][21] = Estado.cadcp1;  //<cadcp1> ::= M<cadcp1>
        this.tabela_de_trasicao[(int)'M'][22] = Estado.cadcp1;  //<cadcp2> ::= M<cadcp1>
        this.tabela_de_trasicao[(int)'N'][0] = Estado.ID;  //<Inicial> ::= N<ID>
        this.tabela_de_trasicao[(int)'N'][1] = Estado.ID;  //<ID> ::= N<ID>
        this.tabela_de_trasicao[(int)'N'][6] = Estado.comp1;  //<comp1> ::= N<comp1>
        this.tabela_de_trasicao[(int)'N'][9] = Estado.comp1;  //<comp2> ::= N<comp1>
        this.tabela_de_trasicao[(int)'N'][12] = Estado.UEV;  //<nump1> ::= N<UEV>
        this.tabela_de_trasicao[(int)'N'][13] = Estado.TMF;  //<nump2> ::= N<TMF>
        this.tabela_de_trasicao[(int)'N'][21] = Estado.cadcp1;  //<cadcp1> ::= N<cadcp1>
        this.tabela_de_trasicao[(int)'N'][22] = Estado.cadcp1;  //<cadcp2> ::= N<cadcp1>
        this.tabela_de_trasicao[(int)'O'][0] = Estado.ID;  //<Inicial> ::= O<ID>
        this.tabela_de_trasicao[(int)'O'][1] = Estado.ID;  //<ID> ::= O<ID>
        this.tabela_de_trasicao[(int)'O'][6] = Estado.comp1;  //<comp1> ::= O<comp1>
        this.tabela_de_trasicao[(int)'O'][9] = Estado.comp1;  //<comp2> ::= O<comp1>
        this.tabela_de_trasicao[(int)'O'][12] = Estado.UEV;  //<nump1> ::= O<UEV>
        this.tabela_de_trasicao[(int)'O'][13] = Estado.TMF;  //<nump2> ::= O<TMF>
        this.tabela_de_trasicao[(int)'O'][21] = Estado.cadcp1;  //<cadcp1> ::= O<cadcp1>
        this.tabela_de_trasicao[(int)'O'][22] = Estado.cadcp1;  //<cadcp2> ::= O<cadcp1>
        this.tabela_de_trasicao[(int)'P'][0] = Estado.ID;  //<Inicial> ::= P<ID>
        this.tabela_de_trasicao[(int)'P'][1] = Estado.ID;  //<ID> ::= P<ID>
        this.tabela_de_trasicao[(int)'P'][6] = Estado.comp1;  //<comp1> ::= P<comp1>
        this.tabela_de_trasicao[(int)'P'][9] = Estado.comp1;  //<comp2> ::= P<comp1>
        this.tabela_de_trasicao[(int)'P'][12] = Estado.UEV;  //<nump1> ::= P<UEV>
        this.tabela_de_trasicao[(int)'P'][13] = Estado.TMF;  //<nump2> ::= P<TMF>
        this.tabela_de_trasicao[(int)'P'][21] = Estado.cadcp1;  //<cadcp1> ::= P<cadcp1>
        this.tabela_de_trasicao[(int)'P'][22] = Estado.cadcp1;  //<cadcp2> ::= P<cadcp1>
        this.tabela_de_trasicao[(int)'Q'][0] = Estado.ID;  //<Inicial> ::= Q<ID>
        this.tabela_de_trasicao[(int)'Q'][1] = Estado.ID;  //<ID> ::= Q<ID>
        this.tabela_de_trasicao[(int)'Q'][6] = Estado.comp1;  //<comp1> ::= Q<comp1>
        this.tabela_de_trasicao[(int)'Q'][9] = Estado.comp1;  //<comp2> ::= Q<comp1>
        this.tabela_de_trasicao[(int)'Q'][12] = Estado.UEV;  //<nump1> ::= Q<UEV>
        this.tabela_de_trasicao[(int)'Q'][13] = Estado.TMF;  //<nump2> ::= Q<TMF>
        this.tabela_de_trasicao[(int)'Q'][21] = Estado.cadcp1;  //<cadcp1> ::= Q<cadcp1>
        this.tabela_de_trasicao[(int)'Q'][22] = Estado.cadcp1;  //<cadcp2> ::= Q<cadcp1>
        this.tabela_de_trasicao[(int)'R'][0] = Estado.ID;  //<Inicial> ::= R<ID>
        this.tabela_de_trasicao[(int)'R'][1] = Estado.ID;  //<ID> ::= R<ID>
        this.tabela_de_trasicao[(int)'R'][6] = Estado.comp1;  //<comp1> ::= R<comp1>
        this.tabela_de_trasicao[(int)'R'][9] = Estado.comp1;  //<comp2> ::= R<comp1>
        this.tabela_de_trasicao[(int)'R'][12] = Estado.UEV;  //<nump1> ::= R<UEV>
        this.tabela_de_trasicao[(int)'R'][13] = Estado.TMF;  //<nump2> ::= R<TMF>
        this.tabela_de_trasicao[(int)'R'][21] = Estado.cadcp1;  //<cadcp1> ::= R<cadcp1>
        this.tabela_de_trasicao[(int)'R'][22] = Estado.cadcp1;  //<cadcp2> ::= R<cadcp1>
        this.tabela_de_trasicao[(int)'S'][0] = Estado.ID;  //<Inicial> ::= S<ID>
        this.tabela_de_trasicao[(int)'S'][1] = Estado.ID;  //<ID> ::= S<ID>
        this.tabela_de_trasicao[(int)'S'][6] = Estado.comp1;  //<comp1> ::= S<comp1>
        this.tabela_de_trasicao[(int)'S'][9] = Estado.comp1;  //<comp2> ::= S<comp1>
        this.tabela_de_trasicao[(int)'S'][12] = Estado.UEV;  //<nump1> ::= S<UEV>
        this.tabela_de_trasicao[(int)'S'][13] = Estado.TMF;  //<nump2> ::= S<TMF>
        this.tabela_de_trasicao[(int)'S'][21] = Estado.cadcp1;  //<cadcp1> ::= S<cadcp1>
        this.tabela_de_trasicao[(int)'S'][22] = Estado.cadcp1;  //<cadcp2> ::= S<cadcp1>
        this.tabela_de_trasicao[(int)'T'][0] = Estado.ID;  //<Inicial> ::= T<ID>
        this.tabela_de_trasicao[(int)'T'][1] = Estado.ID;  //<ID> ::= T<ID>
        this.tabela_de_trasicao[(int)'T'][6] = Estado.comp1;  //<comp1> ::= T<comp1>
        this.tabela_de_trasicao[(int)'T'][9] = Estado.comp1;  //<comp2> ::= T<comp1>
        this.tabela_de_trasicao[(int)'T'][12] = Estado.UEV;  //<nump1> ::= T<UEV>
        this.tabela_de_trasicao[(int)'T'][13] = Estado.TMF;  //<nump2> ::= T<TMF>
        this.tabela_de_trasicao[(int)'T'][21] = Estado.cadcp1;  //<cadcp1> ::= T<cadcp1>
        this.tabela_de_trasicao[(int)'T'][22] = Estado.cadcp1;  //<cadcp2> ::= T<cadcp1>
        this.tabela_de_trasicao[(int)'U'][0] = Estado.ID;  //<Inicial> ::= U<ID>
        this.tabela_de_trasicao[(int)'U'][1] = Estado.ID;  //<ID> ::= U<ID>
        this.tabela_de_trasicao[(int)'U'][6] = Estado.comp1;  //<comp1> ::= U<comp1>
        this.tabela_de_trasicao[(int)'U'][9] = Estado.comp1;  //<comp2> ::= U<comp1>
        this.tabela_de_trasicao[(int)'U'][12] = Estado.UEV;  //<nump1> ::= U<UEV>
        this.tabela_de_trasicao[(int)'U'][13] = Estado.TMF;  //<nump2> ::= U<TMF>
        this.tabela_de_trasicao[(int)'U'][21] = Estado.cadcp1;  //<cadcp1> ::= U<cadcp1>
        this.tabela_de_trasicao[(int)'U'][22] = Estado.cadcp1;  //<cadcp2> ::= U<cadcp1>
        this.tabela_de_trasicao[(int)'V'][0] = Estado.ID;  //<Inicial> ::= V<ID>
        this.tabela_de_trasicao[(int)'V'][1] = Estado.ID;  //<ID> ::= V<ID>
        this.tabela_de_trasicao[(int)'V'][6] = Estado.comp1;  //<comp1> ::= V<comp1>
        this.tabela_de_trasicao[(int)'V'][9] = Estado.comp1;  //<comp2> ::= V<comp1>
        this.tabela_de_trasicao[(int)'V'][12] = Estado.UEV;  //<nump1> ::= V<UEV>
        this.tabela_de_trasicao[(int)'V'][13] = Estado.TMF;  //<nump2> ::= V<TMF>
        this.tabela_de_trasicao[(int)'V'][21] = Estado.cadcp1;  //<cadcp1> ::= V<cadcp1>
        this.tabela_de_trasicao[(int)'V'][22] = Estado.cadcp1;  //<cadcp2> ::= V<cadcp1>
        this.tabela_de_trasicao[(int)'W'][0] = Estado.ID;  //<Inicial> ::= W<ID>
        this.tabela_de_trasicao[(int)'W'][1] = Estado.ID;  //<ID> ::= W<ID>
        this.tabela_de_trasicao[(int)'W'][6] = Estado.comp1;  //<comp1> ::= W<comp1>
        this.tabela_de_trasicao[(int)'W'][9] = Estado.comp1;  //<comp2> ::= W<comp1>
        this.tabela_de_trasicao[(int)'W'][12] = Estado.UEV;  //<nump1> ::= W<UEV>
        this.tabela_de_trasicao[(int)'W'][13] = Estado.TMF;  //<nump2> ::= W<TMF>
        this.tabela_de_trasicao[(int)'W'][21] = Estado.cadcp1;  //<cadcp1> ::= W<cadcp1>
        this.tabela_de_trasicao[(int)'W'][22] = Estado.cadcp1;  //<cadcp2> ::= W<cadcp1>
        this.tabela_de_trasicao[(int)'X'][0] = Estado.ID;  //<Inicial> ::= X<ID>
        this.tabela_de_trasicao[(int)'X'][1] = Estado.ID;  //<ID> ::= X<ID>
        this.tabela_de_trasicao[(int)'X'][6] = Estado.comp1;  //<comp1> ::= X<comp1>
        this.tabela_de_trasicao[(int)'X'][9] = Estado.comp1;  //<comp2> ::= X<comp1>
        this.tabela_de_trasicao[(int)'X'][12] = Estado.UEV;  //<nump1> ::= X<UEV>
        this.tabela_de_trasicao[(int)'X'][13] = Estado.TMF;  //<nump2> ::= X<TMF>
        this.tabela_de_trasicao[(int)'X'][21] = Estado.cadcp1;  //<cadcp1> ::= X<cadcp1>
        this.tabela_de_trasicao[(int)'X'][22] = Estado.cadcp1;  //<cadcp2> ::= X<cadcp1>
        this.tabela_de_trasicao[(int)'Y'][0] = Estado.ID;  //<Inicial> ::= Y<ID>
        this.tabela_de_trasicao[(int)'Y'][1] = Estado.ID;  //<ID> ::= Y<ID>
        this.tabela_de_trasicao[(int)'Y'][6] = Estado.comp1;  //<comp1> ::= Y<comp1>
        this.tabela_de_trasicao[(int)'Y'][9] = Estado.comp1;  //<comp2> ::= Y<comp1>
        this.tabela_de_trasicao[(int)'Y'][12] = Estado.UEV;  //<nump1> ::= Y<UEV>
        this.tabela_de_trasicao[(int)'Y'][13] = Estado.TMF;  //<nump2> ::= Y<TMF>
        this.tabela_de_trasicao[(int)'Y'][21] = Estado.cadcp1;  //<cadcp1> ::= Y<cadcp1>
        this.tabela_de_trasicao[(int)'Y'][22] = Estado.cadcp1;  //<cadcp2> ::= Y<cadcp1>
        this.tabela_de_trasicao[(int)'Z'][0] = Estado.ID;  //<Inicial> ::= Z<ID>
        this.tabela_de_trasicao[(int)'Z'][1] = Estado.ID;  //<ID> ::= Z<ID>
        this.tabela_de_trasicao[(int)'Z'][6] = Estado.comp1;  //<comp1> ::= Z<comp1>
        this.tabela_de_trasicao[(int)'Z'][9] = Estado.comp1;  //<comp2> ::= Z<comp1>
        this.tabela_de_trasicao[(int)'Z'][12] = Estado.UEV;  //<nump1> ::= Z<UEV>
        this.tabela_de_trasicao[(int)'Z'][13] = Estado.TMF;  //<nump2> ::= Z<TMF>
        this.tabela_de_trasicao[(int)'Z'][21] = Estado.cadcp1;  //<cadcp1> ::= Z<cadcp1>
        this.tabela_de_trasicao[(int)'Z'][22] = Estado.cadcp1;  //<cadcp2> ::= Z<cadcp1>
        //this.tabela_de_trasicao[(int)' '][0] = Estado.ID;  //<Inicial> ::=  <ID>
        this.tabela_de_trasicao[(int)' '][6] = Estado.comp1;  //<comp1> ::=  <comp1>
        this.tabela_de_trasicao[(int)' '][9] = Estado.comp1;  //<comp2> ::=  <comp1>
        this.tabela_de_trasicao[(int)' '][12] = Estado.nump1;  //<nump1> ::=  <nump1>
        this.tabela_de_trasicao[(int)' '][13] = Estado.TMF;  //<nump2> ::=  <TMF>
        this.tabela_de_trasicao[(int)' '][17] = Estado.nump1;  //<OPAR3> ::=  <nump1>
        this.tabela_de_trasicao[(int)' '][21] = Estado.cadcp1;  //<cadcp1> ::=  <cadcp1>
        this.tabela_de_trasicao[(int)' '][22] = Estado.cadcp1;  //<cadcp2> ::=  <cadcp1>
        this.tabela_de_trasicao[(int)'0'][1] = Estado.ID;  //<ID> ::= 0<ID>
        this.tabela_de_trasicao[(int)'0'][11] = Estado.NUM;  //<NUM> ::= 0<NUM>
        this.tabela_de_trasicao[(int)'0'][0] = Estado.NUM;  //<Inicial> ::= 0<NUM>
        this.tabela_de_trasicao[(int)'0'][13] = Estado.NUM2;  //<nump2> ::= 0<NUM2>
        this.tabela_de_trasicao[(int)'0'][14] = Estado.NUM2; //<NUM2> ::= 0<NUM2>
        this.tabela_de_trasicao[(int)'1'][0] = Estado.NUM;  //<Inicial> ::= 1<NUM>
        this.tabela_de_trasicao[(int)'1'][1] = Estado.ID;  //<ID> ::= 1<ID>
        this.tabela_de_trasicao[(int)'1'][6] = Estado.comp1;  //<comp1> ::= 1<comp1>
        this.tabela_de_trasicao[(int)'1'][9] = Estado.comp1;  //<comp2> ::= 1<comp1>
        this.tabela_de_trasicao[(int)'1'][11] = Estado.NUM;  //<NUM> ::= 1<NUM>
        this.tabela_de_trasicao[(int)'1'][12] = Estado.NUM;  //<nump1> ::= 1<NUM>
        this.tabela_de_trasicao[(int)'1'][13] = Estado.NUM2;  //<nump2> ::= 1<NUM2>
        this.tabela_de_trasicao[(int)'1'][14] = Estado.NUM2;  //<NUM2> ::= 1<NUM2>
        this.tabela_de_trasicao[(int)'1'][17] = Estado.NUM;  //<OPAR3> ::= 1<NUM>
        this.tabela_de_trasicao[(int)'1'][21] = Estado.cadcp1;  //<cadcp1> ::= 1<cadcp1>
        this.tabela_de_trasicao[(int)'1'][22] = Estado.cadcp1;  //<cadcp2> ::= 1<cadcp1>
        this.tabela_de_trasicao[(int)'2'][0] = Estado.NUM;  //<Inicial> ::= 2<NUM>
        this.tabela_de_trasicao[(int)'2'][1] = Estado.ID;  //<ID> ::= 2<ID>
        this.tabela_de_trasicao[(int)'2'][6] = Estado.comp1;  //<comp1> ::= 2<comp1>
        this.tabela_de_trasicao[(int)'2'][9] = Estado.comp1;  //<comp2> ::= 2<comp1>
        this.tabela_de_trasicao[(int)'2'][11] = Estado.NUM;  //<NUM> ::= 2<NUM>
        this.tabela_de_trasicao[(int)'2'][12] = Estado.NUM;  //<nump1> ::= 2<NUM>
        this.tabela_de_trasicao[(int)'2'][13] = Estado.NUM2;  //<nump2> ::= 2<NUM2>
        this.tabela_de_trasicao[(int)'2'][14] = Estado.NUM2;  //<NUM2> ::= 2<NUM2>
        this.tabela_de_trasicao[(int)'2'][17] = Estado.NUM;  //<OPAR3> ::= 2<NUM>
        this.tabela_de_trasicao[(int)'2'][21] = Estado.cadcp1;  //<cadcp1> ::= 2<cadcp1>
        this.tabela_de_trasicao[(int)'2'][22] = Estado.cadcp1;  //<cadcp2> ::= 2<cadcp1>
        this.tabela_de_trasicao[(int)'3'][0] = Estado.NUM;  //<Inicial> ::= 3<NUM>
        this.tabela_de_trasicao[(int)'3'][1] = Estado.ID;  //<ID> ::= 3<ID>
        this.tabela_de_trasicao[(int)'3'][6] = Estado.comp1;  //<comp1> ::= 3<comp1>
        this.tabela_de_trasicao[(int)'3'][9] = Estado.comp1;  //<comp2> ::= 3<comp1>
        this.tabela_de_trasicao[(int)'3'][11] = Estado.NUM;  //<NUM> ::= 3<NUM>
        this.tabela_de_trasicao[(int)'3'][12] = Estado.NUM;  //<nump1> ::= 3<NUM>
        this.tabela_de_trasicao[(int)'3'][13] = Estado.NUM2;  //<nump2> ::= 3<NUM2>
        this.tabela_de_trasicao[(int)'3'][14] = Estado.NUM2;  //<NUM2> ::= 3<NUM2>
        this.tabela_de_trasicao[(int)'3'][17] = Estado.NUM;  //<OPAR3> ::= 3<NUM>
        this.tabela_de_trasicao[(int)'3'][21] = Estado.cadcp1;  //<cadcp1> ::= 3<cadcp1>
        this.tabela_de_trasicao[(int)'3'][22] = Estado.cadcp1;  //<cadcp2> ::= 3<cadcp1>
        this.tabela_de_trasicao[(int)'4'][0] = Estado.NUM;  //<Inicial> ::= 4<NUM>
        this.tabela_de_trasicao[(int)'4'][1] = Estado.ID;  //<ID> ::= 4<ID>
        this.tabela_de_trasicao[(int)'4'][6] = Estado.comp1;  //<comp1> ::= 4<comp1>
        this.tabela_de_trasicao[(int)'4'][9] = Estado.comp1;  //<comp2> ::= 4<comp1>
        this.tabela_de_trasicao[(int)'4'][11] = Estado.NUM;  //<NUM> ::= 4<NUM>
        this.tabela_de_trasicao[(int)'4'][12] = Estado.NUM;  //<nump1> ::= 4<NUM>
        this.tabela_de_trasicao[(int)'4'][13] = Estado.NUM2;  //<nump2> ::= 4<NUM2>
        this.tabela_de_trasicao[(int)'4'][14] = Estado.NUM2;  //<NUM2> ::= 4<NUM2>
        this.tabela_de_trasicao[(int)'4'][17] = Estado.NUM;  //<OPAR3> ::= 4<NUM>
        this.tabela_de_trasicao[(int)'4'][21] = Estado.cadcp1;  //<cadcp1> ::= 4<cadcp1>
        this.tabela_de_trasicao[(int)'4'][22] = Estado.cadcp1;  //<cadcp2> ::= 4<cadcp1>
        this.tabela_de_trasicao[(int)'5'][0] = Estado.NUM;  //<Inicial> ::= 5<NUM>
        this.tabela_de_trasicao[(int)'5'][1] = Estado.ID;  //<ID> ::= 5<ID>
        this.tabela_de_trasicao[(int)'5'][6] = Estado.comp1;  //<comp1> ::= 5<comp1>
        this.tabela_de_trasicao[(int)'5'][9] = Estado.comp1;  //<comp2> ::= 5<comp1>
        this.tabela_de_trasicao[(int)'5'][11] = Estado.NUM;  //<NUM> ::= 5<NUM>
        this.tabela_de_trasicao[(int)'5'][12] = Estado.NUM;  //<nump1> ::= 5<NUM>
        this.tabela_de_trasicao[(int)'5'][13] = Estado.NUM2;  //<nump2> ::= 5<NUM2>
        this.tabela_de_trasicao[(int)'5'][14] = Estado.NUM2;  //<NUM2> ::= 5<NUM2>
        this.tabela_de_trasicao[(int)'5'][17] = Estado.NUM;  //<OPAR3> ::= 5<NUM>
        this.tabela_de_trasicao[(int)'5'][21] = Estado.cadcp1;  //<cadcp1> ::= 5<cadcp1>
        this.tabela_de_trasicao[(int)'5'][22] = Estado.cadcp1;  //<cadcp2> ::= 5<cadcp1>
        this.tabela_de_trasicao[(int)'6'][0] = Estado.NUM;  //<Inicial> ::= 6<NUM>
        this.tabela_de_trasicao[(int)'6'][1] = Estado.ID;  //<ID> ::= 6<ID>
        this.tabela_de_trasicao[(int)'6'][6] = Estado.comp1;  //<comp1> ::= 6<comp1>
        this.tabela_de_trasicao[(int)'6'][9] = Estado.comp1;  //<comp2> ::= 6<comp1>
        this.tabela_de_trasicao[(int)'6'][11] = Estado.NUM;  //<NUM> ::= 6<NUM>
        this.tabela_de_trasicao[(int)'6'][12] = Estado.NUM;  //<nump1> ::= 6<NUM>
        this.tabela_de_trasicao[(int)'6'][13] = Estado.NUM2;  //<nump2> ::= 6<NUM2>
        this.tabela_de_trasicao[(int)'6'][14] = Estado.NUM2;  //<NUM2> ::= 6<NUM2>
        this.tabela_de_trasicao[(int)'6'][17] = Estado.NUM;  //<OPAR3> ::= 6<NUM>
        this.tabela_de_trasicao[(int)'6'][21] = Estado.cadcp1;  //<cadcp1> ::= 6<cadcp1>
        this.tabela_de_trasicao[(int)'6'][22] = Estado.cadcp1;  //<cadcp2> ::= 6<cadcp1>
        this.tabela_de_trasicao[(int)'7'][0] = Estado.NUM;  //<Inicial> ::= 7<NUM>
        this.tabela_de_trasicao[(int)'7'][1] = Estado.ID;  //<ID> ::= 7<ID>
        this.tabela_de_trasicao[(int)'7'][6] = Estado.comp1;  //<comp1> ::= 7<comp1>
        this.tabela_de_trasicao[(int)'7'][9] = Estado.comp1;  //<comp2> ::= 7<comp1>
        this.tabela_de_trasicao[(int)'7'][11] = Estado.NUM;  //<NUM> ::= 7<NUM>
        this.tabela_de_trasicao[(int)'7'][12] = Estado.NUM;  //<nump1> ::= 7<NUM>
        this.tabela_de_trasicao[(int)'7'][13] = Estado.NUM2;  //<nump2> ::= 7<NUM2>
        this.tabela_de_trasicao[(int)'7'][14] = Estado.NUM2;  //<NUM2> ::= 7<NUM2>
        this.tabela_de_trasicao[(int)'7'][17] = Estado.NUM;  //<OPAR3> ::= 7<NUM>
        this.tabela_de_trasicao[(int)'7'][21] = Estado.cadcp1;  //<cadcp1> ::= 7<cadcp1>
        this.tabela_de_trasicao[(int)'7'][22] = Estado.cadcp1;  //<cadcp2> ::= 7<cadcp1>
        this.tabela_de_trasicao[(int)'8'][0] = Estado.NUM;  //<Inicial> ::= 8<NUM>
        this.tabela_de_trasicao[(int)'8'][1] = Estado.ID;  //<ID> ::= 8<ID>
        this.tabela_de_trasicao[(int)'8'][6] = Estado.comp1;  //<comp1> ::= 8<comp1>
        this.tabela_de_trasicao[(int)'8'][9] = Estado.comp1;  //<comp2> ::= 8<comp1>
        this.tabela_de_trasicao[(int)'8'][11] = Estado.NUM;  //<NUM> ::= 8<NUM>
        this.tabela_de_trasicao[(int)'8'][12] = Estado.NUM;  //<nump1> ::= 8<NUM>
        this.tabela_de_trasicao[(int)'8'][13] = Estado.NUM2;  //<nump2> ::= 8<NUM2>
        this.tabela_de_trasicao[(int)'8'][14] = Estado.NUM2;  //<NUM2> ::= 8<NUM2>
        this.tabela_de_trasicao[(int)'8'][17] = Estado.NUM;  //<OPAR3> ::= 8<NUM>
        this.tabela_de_trasicao[(int)'8'][21] = Estado.cadcp1;  //<cadcp1> ::= 8<cadcp1>
        this.tabela_de_trasicao[(int)'8'][22] = Estado.cadcp1;  //<cadcp2> ::= 8<cadcp1>
        this.tabela_de_trasicao[(int)'9'][0] = Estado.NUM;  //<Inicial> ::= 9<NUM>
        this.tabela_de_trasicao[(int)'9'][1] = Estado.ID;  //<ID> ::= 9<ID>
        this.tabela_de_trasicao[(int)'9'][6] = Estado.comp1;  //<comp1> ::= 9<comp1>
        this.tabela_de_trasicao[(int)'9'][9] = Estado.comp1;  //<comp2> ::= 9<comp1>
        this.tabela_de_trasicao[(int)'9'][11] = Estado.NUM;  //<NUM> ::= 9<NUM>
        this.tabela_de_trasicao[(int)'9'][12] = Estado.NUM;  //<nump1> ::= 9<NUM>
        this.tabela_de_trasicao[(int)'9'][13] = Estado.NUM2;  //<nump2> ::= 9<NUM2>
        this.tabela_de_trasicao[(int)'9'][14] = Estado.NUM2;  //<NUM2> ::= 9<NUM2>
        this.tabela_de_trasicao[(int)'9'][17] = Estado.NUM;  //<OPAR3> ::= 9<NUM>
        this.tabela_de_trasicao[(int)'9'][21] = Estado.cadcp1;  //<cadcp1> ::= 9<cadcp1>
        this.tabela_de_trasicao[(int)'9'][22] = Estado.cadcp1;  //<cadcp2> ::= 9<cadcp1>
        this.tabela_de_trasicao[(int)'_'][1] = Estado.ID;  //<ID> ::= _<ID>
        this.tabela_de_trasicao[(int)'_'][6] = Estado.comp1;  //<comp1> ::= _<comp1>
        this.tabela_de_trasicao[(int)'_'][9] = Estado.comp1;  //<comp2> ::= _<comp1>
        this.tabela_de_trasicao[(int)'_'][12] = Estado.UEV;  //<nump1> ::= _<UEV>
        this.tabela_de_trasicao[(int)'_'][13] = Estado.TMF;  //<nump2> ::= _<TMF>
        this.tabela_de_trasicao[(int)'_'][21] = Estado.cadcp1;  //<cadcp1> ::= _<cadcp1>
        this.tabela_de_trasicao[(int)'_'][22] = Estado.cadcp1;  //<cadcp2> ::= _<cadcp1>
        this.tabela_de_trasicao[(int)';'][0] = Estado.DEL;  //<Inicial> ::= ;<DEL>
        this.tabela_de_trasicao[(int)';'][6] = Estado.comp1;  //<comp1> ::= ;<comp1>
        this.tabela_de_trasicao[(int)';'][9] = Estado.comp1;  //<comp2> ::= ;<comp1>
        this.tabela_de_trasicao[(int)';'][12] = Estado.UEV;  //<nump1> ::= ;<UEV>
        this.tabela_de_trasicao[(int)';'][13] = Estado.TMF;  //<nump2> ::= ;<TMF>
        this.tabela_de_trasicao[(int)';'][21] = Estado.cadcp1;  //<cadcp1> ::= ;<cadcp1>
        this.tabela_de_trasicao[(int)';'][22] = Estado.cadcp1;  //<cadcp2> ::= ;<cadcp1>
        this.tabela_de_trasicao[(int)','][0] = Estado.DEL;  //<Inicial> ::= ,<DEL>
        this.tabela_de_trasicao[(int)','][6] = Estado.comp1;  //<comp1> ::= ,<comp1>
        this.tabela_de_trasicao[(int)','][9] = Estado.comp1;  //<comp2> ::= ,<comp1>
        this.tabela_de_trasicao[(int)','][12] = Estado.UEV;  //<nump1> ::= ,<UEV>
        this.tabela_de_trasicao[(int)','][13] = Estado.TMF;  //<nump2> ::= ,<TMF>
        this.tabela_de_trasicao[(int)','][21] = Estado.cadcp1;  //<cadcp1> ::= ,<cadcp1>
        this.tabela_de_trasicao[(int)','][22] = Estado.cadcp1;  //<cadcp2> ::= ,<cadcp1>
        this.tabela_de_trasicao[(int)'('][0] = Estado.DEL;  //<Inicial> ::= (<DEL>
        this.tabela_de_trasicao[(int)'('][6] = Estado.comp1;  //<comp1> ::= (<comp1>
        this.tabela_de_trasicao[(int)'('][9] = Estado.comp1;  //<comp2> ::= (<comp1>
        this.tabela_de_trasicao[(int)'('][12] = Estado.UEV;  //<nump1> ::= (<UEV>
        this.tabela_de_trasicao[(int)'('][13] = Estado.TMF;  //<nump2> ::= (<TMF>
        this.tabela_de_trasicao[(int)'('][21] = Estado.cadcp1;  //<cadcp1> ::= (<cadcp1>
        this.tabela_de_trasicao[(int)'('][22] = Estado.cadcp1;  //<cadcp2> ::= (<cadcp1>
        this.tabela_de_trasicao[(int)')'][0] = Estado.DEL;  //<Inicial> ::= )<DEL>
        this.tabela_de_trasicao[(int)')'][6] = Estado.comp1;  //<comp1> ::= )<comp1>
        this.tabela_de_trasicao[(int)')'][9] = Estado.comp1;  //<comp2> ::= )<comp1>
        this.tabela_de_trasicao[(int)')'][12] = Estado.UEV;  //<nump1> ::= )<UEV>
        this.tabela_de_trasicao[(int)')'][13] = Estado.TMF;  //<nump2> ::= )<TMF>
        this.tabela_de_trasicao[(int)')'][21] = Estado.cadcp1;  //<cadcp1> ::= )<cadcp1>
        this.tabela_de_trasicao[(int)')'][22] = Estado.cadcp1;  //<cadcp2> ::= )<cadcp1>
        this.tabela_de_trasicao[(int)'['][0] = Estado.DEL;  //<Inicial> ::= [<DEL>
        this.tabela_de_trasicao[(int)'['][6] = Estado.comp1;  //<comp1> ::= [<comp1>
        this.tabela_de_trasicao[(int)'['][9] = Estado.comp1;  //<comp2> ::= [<comp1>
        this.tabela_de_trasicao[(int)'['][12] = Estado.UEV;  //<nump1> ::= [<UEV>
        this.tabela_de_trasicao[(int)'['][13] = Estado.TMF;  //<nump2> ::= [<TMF>
        this.tabela_de_trasicao[(int)'['][21] = Estado.cadcp1;  //<cadcp1> ::= [<cadcp1>
        this.tabela_de_trasicao[(int)'['][22] = Estado.cadcp1;  //<cadcp2> ::= [<cadcp1>
        this.tabela_de_trasicao[(int)']'][0] = Estado.DEL;  //<Inicial> ::= ]<DEL>
        this.tabela_de_trasicao[(int)']'][6] = Estado.comp1;  //<comp1> ::= ]<comp1>
        this.tabela_de_trasicao[(int)']'][9] = Estado.comp1;  //<comp2> ::= ]<comp1>
        this.tabela_de_trasicao[(int)']'][12] = Estado.UEV;  //<nump1> ::= ]<UEV>
        this.tabela_de_trasicao[(int)']'][13] = Estado.TMF;  //<nump2> ::= ]<TMF>
        this.tabela_de_trasicao[(int)']'][21] = Estado.cadcp1;  //<cadcp1> ::= ]<cadcp1>
        this.tabela_de_trasicao[(int)']'][22] = Estado.cadcp1;  //<cadcp2> ::= ]<cadcp1>
        this.tabela_de_trasicao[(int)'{'][0] = Estado.DEL;  //<Inicial> ::= {<DEL>
        this.tabela_de_trasicao[(int)'{'][6] = Estado.comp1;  //<comp1> ::= {<comp1>
        this.tabela_de_trasicao[(int)'{'][9] = Estado.comp1;  //<comp2> ::= {<comp1>
        this.tabela_de_trasicao[(int)'{'][12] = Estado.UEV;  //<nump1> ::= {<UEV>
        this.tabela_de_trasicao[(int)'{'][13] = Estado.TMF;  //<nump2> ::= {<TMF>
        this.tabela_de_trasicao[(int)'{'][21] = Estado.cadcp1;  //<cadcp1> ::= {<cadcp1>
        this.tabela_de_trasicao[(int)'{'][22] = Estado.cadcp1;  //<cadcp2> ::= {<cadcp1>
        this.tabela_de_trasicao[(int)'}'][0] = Estado.DEL;  //<Inicial> ::= }<DEL>
        this.tabela_de_trasicao[(int)'}'][6] = Estado.comp1;  //<comp1> ::= }<comp1>
        this.tabela_de_trasicao[(int)'}'][9] = Estado.comp1;  //<comp2> ::= }<comp1>
        this.tabela_de_trasicao[(int)'}'][12] = Estado.UEV;  //<nump1> ::= }<UEV>
        this.tabela_de_trasicao[(int)'}'][13] = Estado.TMF;  //<nump2> ::= }<TMF>
        this.tabela_de_trasicao[(int)'}'][21] = Estado.cadcp1;  //<cadcp1> ::= }<cadcp1>
        this.tabela_de_trasicao[(int)'}'][22] = Estado.cadcp1;  //<cadcp2> ::= }<cadcp1>
        this.tabela_de_trasicao[(int)'.'][0] = Estado.DEL;  //<Inicial> ::= .<DEL>
        this.tabela_de_trasicao[(int)'.'][6] = Estado.comp1;  //<comp1> ::= .<comp1>
        this.tabela_de_trasicao[(int)'.'][9] = Estado.comp1;  //<comp2> ::= .<comp1>
        this.tabela_de_trasicao[(int)'.'][11] = Estado.nump2;  //<NUM> ::= .<nump2>
        this.tabela_de_trasicao[(int)'.'][12] = Estado.UEV;  //<nump1> ::= .<UEV>
        this.tabela_de_trasicao[(int)'.'][13] = Estado.TMF;  //<nump2> ::= .<TMF>
        this.tabela_de_trasicao[(int)'.'][21] = Estado.cadcp1;  //<cadcp1> ::= .<cadcp1>
        this.tabela_de_trasicao[(int)'.'][13] = Estado.TMF;  //<nump2> ::= .<TMF>
        this.tabela_de_trasicao[(int)'+'][0] = Estado.OPAR;  //<Inicial> ::= +<OPAR>
        this.tabela_de_trasicao[(int)'+'][6] = Estado.comp1;  //<comp1> ::= +<comp1>
        this.tabela_de_trasicao[(int)'+'][7] = Estado.OPAR2;  //<OPAR> ::= +<OPAR2>
        this.tabela_de_trasicao[(int)'+'][9] = Estado.comp1;  //<comp2> ::= +<comp1>
        this.tabela_de_trasicao[(int)'+'][12] = Estado.UEV;  //<nump1> ::= +<UEV>
        this.tabela_de_trasicao[(int)'+'][13] = Estado.TMF;  //<nump2> ::= +<TMF>
        this.tabela_de_trasicao[(int)'+'][21] = Estado.cadcp1;  //<cadcp1> ::= +<cadcp1>
        this.tabela_de_trasicao[(int)'+'][22] = Estado.cadcp1;  //<cadcp2> ::= +<cadcp1>
        this.tabela_de_trasicao[(int)'*'][0] = Estado.OPAR;  //<Inicial> ::= *<OPAR>
        this.tabela_de_trasicao[(int)'*'][6] = Estado.comp2;  //<comp1> ::= *<comp2>
        this.tabela_de_trasicao[(int)'*'][7] = Estado.comp1;  //<OPAR> ::= *<comp1>
        this.tabela_de_trasicao[(int)'*'][9] = Estado.comp1;  //<comp2> ::= *<comp1>
        this.tabela_de_trasicao[(int)'*'][12] = Estado.UEV;  //<nump1> ::= *<UEV>
        this.tabela_de_trasicao[(int)'*'][13] = Estado.TMF;  //<nump2> ::= *<TMF>
        this.tabela_de_trasicao[(int)'*'][21] = Estado.cadcp1;  //<cadcp1> ::= *<cadcp1>
        this.tabela_de_trasicao[(int)'*'][22] = Estado.cadcp1;  //<cadcp2> ::= *<cadcp1>
        this.tabela_de_trasicao[(int)'/'][0] = Estado.OPAR;  //<Inicial> ::= /<OPAR>
        this.tabela_de_trasicao[(int)'/'][6] = Estado.comp1;  //<comp1> ::= /<comp1>
        this.tabela_de_trasicao[(int)'/'][7] = Estado.COML;  //<OPAR> ::= /<COML>
        this.tabela_de_trasicao[(int)'/'][9] = Estado.COMB;  //<comp2> ::= /<COMB>
        this.tabela_de_trasicao[(int)'/'][12] = Estado.UEV;  //<nump1> ::= /<UEV>
        this.tabela_de_trasicao[(int)'/'][13] = Estado.TMF;  //<nump2> ::= /<TMF>
        this.tabela_de_trasicao[(int)'/'][21] = Estado.cadcp1;  //<cadcp1> ::= /<cadcp1>
        this.tabela_de_trasicao[(int)'/'][22] = Estado.cadcp1;  //<cadcp2> ::= /<cadcp1>
        this.tabela_de_trasicao[(int)'!'][0] = Estado.OPL;  //<Inicial> ::= !<OPL>
        this.tabela_de_trasicao[(int)'!'][6] = Estado.comp1;  //<comp1> ::= !<comp1>
        this.tabela_de_trasicao[(int)'!'][9] = Estado.comp1;  //<comp2> ::= !<comp1>
        this.tabela_de_trasicao[(int)'!'][12] = Estado.UEV;  //<nump1> ::= !<UEV>
        this.tabela_de_trasicao[(int)'!'][13] = Estado.TMF;  //<nump2> ::= !<TMF>
        this.tabela_de_trasicao[(int)'!'][21] = Estado.cadcp1;  //<cadcp1> ::= !<cadcp1>
        this.tabela_de_trasicao[(int)'!'][22] = Estado.cadcp1;  //<cadcp2> ::= !<cadcp1>
        this.tabela_de_trasicao[(int)'"'][0] = Estado.cadcp1;  //<Inicial> ::= "<cadcp1>
        this.tabela_de_trasicao[(int)'"'][6] = Estado.comp1;  //<comp1> ::= "<comp1>
        this.tabela_de_trasicao[(int)'"'][9] = Estado.comp1;  //<comp2> ::= "<comp1>
        this.tabela_de_trasicao[(int)'"'][12] = Estado.UEV;  //<nump1> ::= "<UEV>
        this.tabela_de_trasicao[(int)'"'][13] = Estado.TMF;  //<nump2> ::= "<TMF>
        this.tabela_de_trasicao[(int)'"'][21] = Estado.CADC;  //<cadcp1> ::= "<CADC>
        this.tabela_de_trasicao[(int)'"'][22] = Estado.cadcp1;  //<cadcp2> ::= "<cadcp1>
        this.tabela_de_trasicao[(int)'#'][6] = Estado.comp1;  //<comp1> ::= #<comp1>
        this.tabela_de_trasicao[(int)'#'][9] = Estado.comp1;  //<comp2> ::= #<comp1>
        this.tabela_de_trasicao[(int)'#'][12] = Estado.UEV;  //<nump1> ::= #<UEV>
        this.tabela_de_trasicao[(int)'#'][13] = Estado.TMF;  //<nump2> ::= #<TMF>
        this.tabela_de_trasicao[(int)'#'][21] = Estado.cadcp1;  //<cadcp1> ::= #<cadcp1>
        this.tabela_de_trasicao[(int)'#'][22] = Estado.cadcp1;  //<cadcp2> ::= #<cadcp1>
        this.tabela_de_trasicao[(int)'$'][6] = Estado.comp1;  //<comp1> ::= $<comp1>
        this.tabela_de_trasicao[(int)'$'][9] = Estado.comp1;  //<comp2> ::= $<comp1>
        this.tabela_de_trasicao[(int)'$'][12] = Estado.UEV;  //<nump1> ::= $<UEV>
        this.tabela_de_trasicao[(int)'$'][13] = Estado.TMF;  //<nump2> ::= $<TMF>
        this.tabela_de_trasicao[(int)'$'][21] = Estado.cadcp1;  //<cadcp1> ::= $<cadcp1>
        this.tabela_de_trasicao[(int)'$'][22] = Estado.cadcp1;  //<cadcp2> ::= $<cadcp1>
        this.tabela_de_trasicao[(int)'%'][6] = Estado.comp1;  //<comp1> ::= %<comp1>
        this.tabela_de_trasicao[(int)'%'][9] = Estado.comp1;  //<comp2> ::= %<comp1>
        this.tabela_de_trasicao[(int)'%'][12] = Estado.UEV;  //<nump1> ::= %<UEV>
        this.tabela_de_trasicao[(int)'%'][13] = Estado.TMF;  //<nump2> ::= %<TMF>
        this.tabela_de_trasicao[(int)'%'][21] = Estado.cadcp1;  //<cadcp1> ::= %<cadcp1>
        this.tabela_de_trasicao[(int)'%'][22] = Estado.cadcp1;  //<cadcp2> ::= %<cadcp1>
        this.tabela_de_trasicao[(int)'&'][0] = Estado.oplp;  //<Inicial> ::= &<oplp>
        this.tabela_de_trasicao[(int)'&'][6] = Estado.comp1;  //<comp1> ::= &<comp1>
        this.tabela_de_trasicao[(int)'&'][9] = Estado.comp1;  //<comp2> ::= &<comp1>
        this.tabela_de_trasicao[(int)'&'][12] = Estado.UEV;  //<nump1> ::= &<UEV>
        this.tabela_de_trasicao[(int)'&'][13] = Estado.TMF;  //<nump2> ::= &<TMF>
        this.tabela_de_trasicao[(int)'&'][20] = Estado.OPL2;  //<oplp> ::= &<OPL2>
        this.tabela_de_trasicao[(int)'&'][21] = Estado.cadcp1;  //<cadcp1> ::= &<cadcp1>
        this.tabela_de_trasicao[(int)'&'][22] = Estado.cadcp1;  //<cadcp2> ::= &<cadcp1>
        this.tabela_de_trasicao[(int)'-'][0] = Estado.OPAR3;  //<Inicial> ::= -<OPAR3>
        this.tabela_de_trasicao[(int)'-'][6] = Estado.comp1;  //<comp1> ::= -<comp1>
        this.tabela_de_trasicao[(int)'-'][9] = Estado.comp1;  //<comp2> ::= -<comp1>
        this.tabela_de_trasicao[(int)'-'][12] = Estado.UEV;  //<nump1> ::= -<UEV>
        this.tabela_de_trasicao[(int)'-'][13] = Estado.TMF;  //<nump2> ::= -<TMF>
        this.tabela_de_trasicao[(int)'-'][17] = Estado.OPAR2;  //<OPAR3> ::= -<OPAR2>
        this.tabela_de_trasicao[(int)'-'][21] = Estado.cadcp1;  //<cadcp1> ::= -<cadcp1>
        this.tabela_de_trasicao[(int)'-'][22] = Estado.cadcp1;  //<cadcp2> ::= -<cadcp1>
        this.tabela_de_trasicao[(int)':'][6] = Estado.comp1;  //<comp1> ::= :<comp1>
        this.tabela_de_trasicao[(int)':'][9] = Estado.comp1;  //<comp2> ::= :<comp1>
        this.tabela_de_trasicao[(int)':'][12] = Estado.UEV;  //<nump1> ::= :<UEV>
        this.tabela_de_trasicao[(int)':'][13] = Estado.TMF;  //<nump2> ::= :<TMF>
        this.tabela_de_trasicao[(int)':'][21] = Estado.cadcp1;  //<cadcp1> ::= :<cadcp1>
        this.tabela_de_trasicao[(int)':'][22] = Estado.cadcp1;  //<cadcp2> ::= :<cadcp1>
        this.tabela_de_trasicao[(int)'<'][0] = Estado.OPRL;  //<Inicial> ::= <<OPRL>
        this.tabela_de_trasicao[(int)'<'][6] = Estado.comp1;  //<comp1> ::= <<comp1>
        this.tabela_de_trasicao[(int)'<'][9] = Estado.comp1;  //<comp2> ::= <<comp1>
        this.tabela_de_trasicao[(int)'<'][12] = Estado.UEV;  //<nump1> ::= <<UEV>
        this.tabela_de_trasicao[(int)'<'][13] = Estado.TMF;  //<nump2> ::= <<TMF>
        this.tabela_de_trasicao[(int)'<'][21] = Estado.cadcp1;  //<cadcp1> ::= <<cadcp1>
        this.tabela_de_trasicao[(int)'<'][22] = Estado.cadcp1;  //<cadcp2> ::= <<cadcp1>
        this.tabela_de_trasicao[(int)'='][0] = Estado.OPRL;  //<Inicial> ::= =<OPRL>
        this.tabela_de_trasicao[(int)'='][6] = Estado.comp1;  //<comp1> ::= =<comp1>
        this.tabela_de_trasicao[(int)'='][9] = Estado.comp1;  //<comp2> ::= =<comp1>
        this.tabela_de_trasicao[(int)'='][12] = Estado.UEV;  //<nump1> ::= =<UEV>
        this.tabela_de_trasicao[(int)'='][13] = Estado.TMF;  //<nump2> ::= =<TMF>
        this.tabela_de_trasicao[(int)'='][15] = Estado.OPRL2;  //<OPRL> ::= =<OPRL2>
        this.tabela_de_trasicao[(int)'='][18] = Estado.OPRL2;  //<OPL> ::= =<OPRL2>
        this.tabela_de_trasicao[(int)'='][21] = Estado.cadcp1;  //<cadcp1> ::= =<cadcp1>
        this.tabela_de_trasicao[(int)'='][22] = Estado.cadcp1;  //<cadcp2> ::= =<cadcp1>
        this.tabela_de_trasicao[(int)'>'][0] = Estado.OPRL;  //<Inicial> ::= ><OPRL>
        this.tabela_de_trasicao[(int)'>'][6] = Estado.comp1;  //<comp1> ::= ><comp1>
        this.tabela_de_trasicao[(int)'>'][9] = Estado.comp1;  //<comp2> ::= ><comp1>
        this.tabela_de_trasicao[(int)'>'][12] = Estado.UEV;  //<nump1> ::= ><UEV>
        this.tabela_de_trasicao[(int)'>'][13] = Estado.TMF;  //<nump2> ::= ><TMF>
        this.tabela_de_trasicao[(int)'>'][21] = Estado.cadcp1;  //<cadcp1> ::= ><cadcp1>
        this.tabela_de_trasicao[(int)'>'][22] = Estado.cadcp1;  //<cadcp2> ::= ><cadcp1>
        this.tabela_de_trasicao[(int)'?'][6] = Estado.comp1;  //<comp1> ::= ?<comp1>
        this.tabela_de_trasicao[(int)'?'][9] = Estado.comp1;  //<comp2> ::= ?<comp1>
        this.tabela_de_trasicao[(int)'?'][12] = Estado.UEV;  //<nump1> ::= ?<UEV>
        this.tabela_de_trasicao[(int)'?'][13] = Estado.TMF;  //<nump2> ::= ?<TMF>
        this.tabela_de_trasicao[(int)'?'][21] = Estado.cadcp1;  //<cadcp1> ::= ?<cadcp1>
        this.tabela_de_trasicao[(int)'?'][22] = Estado.cadcp1;  //<cadcp2> ::= ?<cadcp1>
        this.tabela_de_trasicao[(int)'@'][6] = Estado.comp1;  //<comp1> ::= @<comp1>
        this.tabela_de_trasicao[(int)'@'][9] = Estado.comp1;  //<comp2> ::= @<comp1>
        this.tabela_de_trasicao[(int)'@'][12] = Estado.UEV;  //<nump1> ::= @<UEV>
        this.tabela_de_trasicao[(int)'@'][13] = Estado.TMF;  //<nump2> ::= @<TMF>
        this.tabela_de_trasicao[(int)'@'][21] = Estado.cadcp1;  //<cadcp1> ::= @<cadcp1>
        this.tabela_de_trasicao[(int)'@'][22] = Estado.cadcp1;  //<cadcp2> ::= @<cadcp1>
        this.tabela_de_trasicao[(int)'\\'][6] = Estado.comp1;  //<comp1> ::= \<comp1>
        this.tabela_de_trasicao[(int)'\\'][9] = Estado.comp1;  //<comp2> ::= \<comp1>
        this.tabela_de_trasicao[(int)'\\'][12] = Estado.UEV;  //<nump1> ::= \<UEV>
        this.tabela_de_trasicao[(int)'\\'][13] = Estado.TMF;  //<nump2> ::= \<TMF>
        this.tabela_de_trasicao[(int)'\\'][21] = Estado.cadcp2;  //<cadcp1> ::= \<cadcp2>
        this.tabela_de_trasicao[(int)'\\'][22] = Estado.cadcp1;  //<cadcp2> ::= \<cadcp1>
        this.tabela_de_trasicao[(int)'^'][6] = Estado.comp1;  //<comp1> ::= ^<comp1>
        this.tabela_de_trasicao[(int)'^'][9] = Estado.comp1;  //<comp2> ::= ^<comp1>
        this.tabela_de_trasicao[(int)'^'][12] = Estado.UEV;  //<nump1> ::= ^<UEV>
        this.tabela_de_trasicao[(int)'^'][13] = Estado.TMF;  //<nump2> ::= ^<TMF>
        this.tabela_de_trasicao[(int)'^'][21] = Estado.cadcp1;  //<cadcp1> ::= ^<cadcp1>
        this.tabela_de_trasicao[(int)'^'][22] = Estado.cadcp1;  //<cadcp2> ::= ^<cadcp1>
        this.tabela_de_trasicao[(int)'`'][6] = Estado.comp1;  //<comp1> ::= `<comp1>
        this.tabela_de_trasicao[(int)'`'][9] = Estado.comp1;  //<comp2> ::= `<comp1>
        this.tabela_de_trasicao[(int)'`'][12] = Estado.UEV;  //<nump1> ::= `<UEV>
        this.tabela_de_trasicao[(int)'`'][13] = Estado.TMF;  //<nump2> ::= `<TMF>
        this.tabela_de_trasicao[(int)'`'][21] = Estado.cadcp1;  //<cadcp1> ::= `<cadcp1>
        this.tabela_de_trasicao[(int)'`'][22] = Estado.cadcp1;  //<cadcp2> ::= `<cadcp1>
        this.tabela_de_trasicao[(int)'|'][0] = Estado.oplp;  //<Inicial> ::= |<oplp>
        this.tabela_de_trasicao[(int)'|'][6] = Estado.comp1;  //<comp1> ::= |<comp1>
        this.tabela_de_trasicao[(int)'|'][9] = Estado.comp1;  //<comp2> ::= |<comp1>
        this.tabela_de_trasicao[(int)'|'][12] = Estado.UEV;  //<nump1> ::= |<UEV>
        this.tabela_de_trasicao[(int)'|'][13] = Estado.TMF;  //<nump2> ::= |<TMF>
        this.tabela_de_trasicao[(int)'|'][20] = Estado.OPL2;  //<oplp> ::= |<OPL2>
        this.tabela_de_trasicao[(int)'|'][21] = Estado.cadcp1;  //<cadcp1> ::= |<cadcp1>
        this.tabela_de_trasicao[(int)'|'][22] = Estado.cadcp1;  //<cadcp2> ::= |<cadcp1>
        this.tabela_de_trasicao[(int)'~'][6] = Estado.comp1;  //<comp1> ::= ~<comp1>
        this.tabela_de_trasicao[(int)'~'][9] = Estado.comp1;  //<comp2> ::= ~<comp1>
        this.tabela_de_trasicao[(int)'~'][12] = Estado.UEV;  //<nump1> ::= ~<UEV>
        this.tabela_de_trasicao[(int)'~'][13] = Estado.TMF;  //<nump2> ::= ~<TMF>
        this.tabela_de_trasicao[(int)'~'][21] = Estado.cadcp1;  //<cadcp1> ::= ~<cadcp1>
        this.tabela_de_trasicao[(int)'~'][22] = Estado.cadcp1;  //<cadcp2> ::= ~<cadcp1>
        this.tabela_de_trasicao[(int)'\n'][9] = Estado.comp1;  //<comp2> ::= \n<comp1>
        this.tabela_de_trasicao[(int)'\n'][6] = Estado.comp1;  //<comp1> ::= ~<comp1>

    }

    public Estado transicao(Estado estado_inicial, char entrada){
        return this.tabela_de_trasicao[(int)entrada][estado_inicial.getEstadoValor()];
    }
    public boolean isFinal(Estado estado){
        for (int valor : this.estados_finais){
            if(estado.getEstadoValor() == valor){
                return true;
            }
        }
        return false;
    }

    public boolean isPalavraReservada(String lexema) {
        for (String palavra_reservada : this.palavras_reservadas) {
            if(palavra_reservada.equals(lexema)){
                return true;
            }
        }
        return false;
    }
}
